# Generated by Django 3.2.9 on 2022-01-04 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=144)),
                ('description', models.TextField()),
                ('precio', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='productos')),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('category_slug', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=144)),
                ('apellido', models.CharField(max_length=144)),
                ('correo', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=150)),
                ('isActive', models.BooleanField()),
                ('image', models.ImageField(null=True, upload_to='usuarios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(choices=[('INF', 'Infantiles'), ('FAM', 'Familiares'), ('NAP', 'Naipes'), ('TOD', 'Todos los Juegos')], default='TOD', max_length=4)),
                ('key_catogory_list', models.ManyToManyField(to='app.Products')),
            ],
        ),
    ]
