# Generated by Django 3.2.9 on 2022-01-13 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='producto',
        ),
        migrations.CreateModel(
            name='CantidadProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='cantidad_productos',
            field=models.ManyToManyField(to='app.CantidadProducto'),
        ),
    ]
